name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scraper/requirements.txt
  
      - name: Test
        run: pytest .
        working-directory: ./scraper

      - name: Run scrape
        run: python main.py
        working-directory: ./scraper
      
      - name: Zip scraped data
        run: zip scraped-data.zip -r out/
        working-directory: ./scraper
        
      - name: Upload scraped data
        uses: actions/upload-artifact@v2.2.0
        with: 
          name: Scraped Data
          path: ./scraper/scraped-data.zip
